ARG ROS_DISTRO=kilted
FROM osrf/ros:${ROS_DISTRO}-desktop-full

ARG USERID=1000
ARG USER=admin
ARG ROS_DISTRO

######################
# 1) Environment
######################
ENV TERM=linux
ENV DEBIAN_FRONTEND=noninteractive
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

######################
# 2) Install
######################
COPY docker/requirements.txt .
RUN apt-get update && apt-get install --no-install-recommends -y $(cat requirements.txt) && rm requirements.txt

RUN sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list'
RUN wget http://packages.osrfoundation.org/gazebo.key -O - | apt-key add -
RUN apt-get update && apt-get install --no-install-recommends -y gz-ionic

######################
# 3) User
######################
RUN if id -u "$USER" >/dev/null 2>&1; then \
		usermod --uid "$USERID" "$USER"; \
	else \
		EXISTING_USER="$(getent passwd "$USERID" | cut -d: -f1 || true)"; \
		if [ -n "$EXISTING_USER" ]; then \
			usermod -l "$USER" "$EXISTING_USER"; \
			usermod -d "/home/$USER" -m "$USER"; \
		else \
			adduser --uid "$USERID" --gecos "admin" --disabled-password "$USER"; \
		fi; \
	fi \
	&& usermod -a -G sudo,dialout,plugdev "$USER" \
	&& (grep -qxF '%sudo ALL=(ALL) NOPASSWD:ALL' /etc/sudoers || echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers)
USER $USER

######################
# 4) Update
######################
RUN sudo apt-get update && sudo apt-get upgrade -y && rosdep update

######################
# 5) Gits and Sources
######################
RUN mkdir -p /home/$USER/ros_ws/src /home/$USER/ros_ws/build /home/$USER/ros_ws/install /home/$USER/ros_ws/log
WORKDIR /home/$USER/ros_ws/src

RUN git clone https://github.com/orka375/eta_gz.git

WORKDIR /home/$USER/ros_ws/
RUN . /opt/ros/${ROS_DISTRO}/setup.sh && colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release



RUN gz fuel download --url "https://fuel.gazebosim.org/1.0/OpenRobotics/models/officedesk"
RUN gz fuel download --url "https://fuel.gazebosim.org/1.0/OpenRobotics/models/officechair"
RUN gz fuel download --url "https://fuel.gazebosim.org/1.0/OpenRobotics/models/diningtable"
RUN gz fuel download --url "https://fuel.gazebosim.org/1.0/OpenRobotics/models/foodcourttable1"
RUN gz fuel download --url "https://fuel.gazebosim.org/1.0/OpenRobotics/models/depot"
RUN gz fuel download --url "https://fuel.gazebosim.org/1.0/malbonico/models/table"
RUN gz fuel download --url "https://fuel.gazebosim.org/1.0/openrobotics/models/fridge/2"
RUN gz fuel download --url "https://fuel.gazebosim.org/1.0/openrobotics/models/table/4"
RUN gz fuel download --url "https://fuel.gazebosim.org/1.0/makerspet/models/tv_65in/1"
RUN gz fuel download --url "https://fuel.gazebosim.org/1.0/openrobotics/models/table/4"


######################
# 6) Bashrc
######################
RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> /home/$USER/.bashrc
RUN echo "source /home/$USER/ros_ws/install/setup.bash" >> /home/$USER/.bashrc
RUN echo "source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash" >> /home/$USER/.bashrc
RUN echo "export ROS_DOMAIN_ID=1" >> /home/$USER/.bashrc
RUN echo "export QT_X11_NO_MITSHM=1" >> /home/$USER/.bashrc
RUN echo "export IGN_IP=127.0.0.1" >> /home/$USER/.bashrc

######################
# 7) Pip
######################
# No additional pip packages are required in this image.

######################
# 8) Workspace
######################


WORKDIR /home/$USER/ros_ws

CMD ["/bin/bash"]
