FROM osrf/ros:kilted-desktop-full

# Arguments for building
ARG USERID
ARG USER

# Setup environment
ENV TERM linux
ENV DEBIAN_FRONTEND noninteractive
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

# Copy requirement files and install dependencies
COPY docker/requirements.txt .
RUN apt-get update && apt-get install --no-install-recommends -y $(cat requirements.txt)
RUN rm requirements.txt

RUN echo "export ROS_DOMAIN_ID=1" >> /home/$USER/.bashrc

# Install Gazebo Fortress
RUN sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list'
RUN wget http://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -
RUN sudo apt-get update
RUN sudo apt-get install gz-ionic -y

# Create a user with passwordless sudo
RUN adduser --gecos "ekumen developer" --disabled-password $USER
RUN adduser $USER sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
RUN echo "export QT_X11_NO_MITSHM=1" >> /home/$USER/.bashrc
RUN echo "export IGN_IP=127.0.0.1" >> /home/$USER/.bashrc
USER $USER

# Adds USER to dialout and plugdev group.
# This is needed to access the serial ports, for further references check
# the libserial documentation.
RUN sudo usermod -a -G dialout $USER
RUN sudo usermod -a -G plugdev $USER

# Creates the src folder of the workspace.
RUN mkdir -p /home/$USER/ws/src

# Adds to bashrc the ros kilted overlay sourcing.
RUN echo "source /opt/ros/kilted/setup.bash" >> /home/$USER/.bashrc
# Adds colcon autocomplete
RUN echo "source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash" >> /home/$USER/.bashrc

# Updates
RUN sudo apt upgrade -y && sudo apt update && rosdep update

# Download models from fuel
RUN gz fuel download --url "https://fuel.gazebosim.org/1.0/OpenRobotics/models/officedesk"
RUN gz fuel download --url "https://fuel.gazebosim.org/1.0/OpenRobotics/models/officechair"
RUN gz fuel download --url "https://fuel.gazebosim.org/1.0/OpenRobotics/models/diningtable"
RUN gz fuel download --url "https://fuel.gazebosim.org/1.0/OpenRobotics/models/foodcourttable1"
RUN gz fuel download --url "https://fuel.gazebosim.org/1.0/OpenRobotics/models/depot"
RUN gz fuel download --url "https://fuel.gazebosim.org/1.0/malbonico/models/table"
RUN gz fuel download --url "https://fuel.gazebosim.org/1.0/openrobotics/models/fridge/2"
RUN gz fuel download --url "https://fuel.gazebosim.org/1.0/openrobotics/models/table/4"
RUN gz fuel download --url "https://fuel.gazebosim.org/1.0/makerspet/models/tv_65in/1"
RUN gz fuel download --url "https://fuel.gazebosim.org/1.0/openrobotics/models/table/4"

# Defines a workspace folder.
WORKDIR /home/$USER/ws

CMD ["/bin/bash"]
